[general]
log_level = "DEBUG"
use_elevation = true
num_workers = 12
timezone = +3

[endpoints]
TLE_URL = "https://live.ariss.org/iss.txt"
ELEVATION_URL = "https://api.open-meteo.com/v1/elevation?latitude={lat}&longitude={lon}"

[coordinates]
latitude = 55.930591
longitude = 37.498435
